spring:
  datasource:
    url: jdbc:mysql://localhost:3307/cinema
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8082
  
---
spring:
  profiles:
  - dev
  - docker

---
spring:
  profiles: dev

server:
  port: 7700